### ISSUE TITLE
Cleaning up the sidebar in the wiki

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bids-starter-kit#100]
Hi @Park-Patrick @dorahermes @emdupre - and anyone else who is following the development!

I think the sidebar in the wiki contains too many links - it's scrolling off the bottom of the screen and isn't really as useful as you'd hope it to be.

Here's a list of what's on it right now:

---

**[Home](https://github.com/bids-standard/bids-starter-kit/wiki)**

**[Frequently Asked Questions](FAQ)**

**[Glossary](Glossary)**

**[The BIDS Folder Hierarchy](The-BIDS-folder-hierarchy)**
*A guide to the different files and how they are organised in the BIDS directory structure*

**[Tutorials](Tutorials)**
*Links to detailed tutorials to help you get started with BIDS*

**[Metadata File Formats](Metadata-file-formats)**
*About JSON and TSV files and creating/reading them*

**[Dataset Examples](dataset-examples)**
*Links to BIDS compliant datasets with some sourcedata*

**[EEG Formatting Examples](EEG-Formatting-Examples)**

**[BIDS Validator Info](bids-validator-info)**

**[BIDS Apps Help](BIDS-Apps-Help)**
*Helpful links and a FAQ about BIDS Apps*

**[BIDS Extensions](BIDS-Extentions)**

**[Publications](Publications)**

**[Community Resources](community-resources)**
*A collection of resources from the community including slideshows / presentations / graphics / etc*

**[Useful Links](Useful-links)**
*A collection of links to useful code / other repositories relevant to BIDS*

**[Contact](Contact)**

---

Note that I've done a little re-formatting (taken out header formatting and just made links bold) to make it take up a little less space, but I'd like to propose that we shorten this list to:

---

**[Home](https://github.com/bids-standard/bids-starter-kit/wiki)**

**[Frequently Asked Questions](FAQ)**

**[Glossary](Glossary)**

**[The BIDS Folder Hierarchy](The-BIDS-folder-hierarchy)**
*A guide to the different files and how they are organised in the BIDS directory structure*

**[Tutorials](Tutorials)**
*Links to detailed tutorials to help you get started with BIDS*

**[Metadata File Formats](Metadata-file-formats)**
*About JSON and TSV files and creating/reading them*

**[Dataset Examples](dataset-examples)**
*Links to BIDS compliant datasets with some sourcedata*

**[BIDS Apps Help](BIDS-Apps-Help)**
*Helpful links and a FAQ about BIDS Apps*

**[BIDS Extensions](BIDS-Extentions)**
*More information about how to add to the BIDS specification*

**[Community Resources](community-resources)**
*A collection of resources from the community including slideshows / presentations / graphics / etc*

**[Contact](Contact)**
*Get in touch!*

---

I've also updated the [wiki home page](https://github.com/bids-standard/bids-starter-kit/wiki) to point to the pages dropdown menu that shows **all** the pages so maybe they're easier to find that way?

What do you all think?

**Comment by emdupre** [comment]
I think the modified listing looks great ! Thanks so much for updating it :smile: 
What do you think about adding a title to the sidebar, something like "Quick Links" or "Frequently Visited" ? I think that could further distinguish it from the pages dropdown menu (which is a great addition !).

**Comment by dorahermes** [comment]
Thanks for cleaning this up! The BIDS-EEG extension was adding some very useful files for creating EEG-BIDS metadata files and they asked about where to put add instructions for 'EEG Formatting Examples' @robertoostenveld @sappelhoff 

I noticed that this header was removed, but I think we'll need that somewhere, any suggestions on where this should go in the cleaner list?

**Comment by sappelhoff** [comment]
maybe under "frequently asked questions"?

- "how to format Hardware and Software filter fields in a .json?"
- "how to report EEGReference for Biosemi data?"

**Comment by dorahermes** [comment]
+1 to @sappelhoff Can you add these questions?
When you add them, maybe add a section header with EEG/MEG/iEEG specific questions?

@KirstieJane 
Would the current Useful Links merge into Community Resources?

**Comment by sappelhoff** [comment]
see: https://github.com/bids-standard/bids-starter-kit/wiki/FAQ---Frequently-Asked-Questions

so far there are only 2 FAQs so I didn't split them into subcategories so much ... this is something we can do as soon as we get more and more FAQs and corresponding examples.

@KirstieJane feel free to use "https://github.com/bids-standard/bids-starter-kit/wiki/FAQ---Frequently-Asked-Questions" in the new WIKI ... I deleted the " EEG Formatting Examples" page.

**Comment by Remi-Gau** [comment]
closing this as obsolete (especially if moving away from the wiki)
