### ISSUE TITLE
example for EEG has spaces in the json field for hardware filters

### ISSUE THREAD

**Issue by dorahermes** [bids-standard/bids-starter-kit#102]
@sappelhoff 
There are spaces in the EEG example for the hardware filters. This should be CamelCase. Can I change this?

**Comment by sappelhoff** [comment]
What exactly do you want to change?

https://github.com/bids-standard/bids-starter-kit/blob/2711f87260851a2d2da2b1829cb847883b220d5e/templates/sub-01/ses-01/eeg/sub-01_ses-01_task-FilterExample_eeg.json#L1-L9

generally, it should be fine - but I don't know whether it is *necessary*. As far as I know, only the top level keys **must** be camel case. Or should all keys always be camelCase?

**Comment by dorahermes** [comment]
I would prefer something like this, for consistency, and add a note that frequencies SHOULD be expressed in Hz, so no need to specify that in the json:

{ 
     "HardwareFilters": { 
         "HighpassRCfilter": { 
             "HalfAmplitudeCutoff": 0.0159, 
             "Rolloff": "6dB/Octave" 
         } 
     }, 
     "SoftwareFilters": "n/a" 
 }

**Comment by sappelhoff** [comment]
Okay, that would be fine by me. What is your general view on this way to define filters? So far, I didn't get a lot of feedback

**Comment by dorahermes** [comment]
I think it is helpful, but potentially a little much to be required (as per comment on the BIDS-iEEG extension) and we had another question from @voytek about how to specify DC removal

**Comment by sappelhoff** [comment]
> another question from @voytek about how to specify DC removal

mh we could either have a new key for it e.g.,

```json
{
    DCOffset: "The DC Offset was removed through ... "
}
```

Or we could somehow integrate this information with `HardwareFilters`, but that'd better be discussed in the specification.

> I think it is helpful, but potentially a little much to be required

mmmh okay let's wait for good alternatives in the spec then. I'll adjust this example once we converge on a solution. 

In the meantime, feel free to adjust the camelCase if you like.

**Comment by dorahermes** [comment]
Ok, I changed this to CamesCase and will close this issue. I will add comments on DC Offset and HardwareFilters in the spec.
