### ISSUE TITLE
bidskit

### ISSUE THREAD

**Issue by yonestar** [bids-standard/bids-starter-kit#103]
Hi,

This is a great resource!  Thank you.  I also wanted to give a shoutout to bidskit -- I have been using it to convert my raw dicoms to BIDS format, and its great. (I am not involved in its development).  Others visiting this page might be interested in the bidskit tool as well!

Yoni

**Comment by dorahermes** [comment]
Thanks! @yonestar is this the correct link: https://github.com/jmtyszka/bidskit
We can definitely add it in the wiki!

**Comment by dorahermes** [comment]
Thanks! it's added to the wiki

**Comment by Remi-Gau** [comment]
@all-contributors please add @yonestar for idea
