### ISSUE TITLE
script to convert SPM outputs into BIDS derivatives 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#108]
Am playing catch up with the BIDS derivatives RC1 trying to wrap my head around it to structure some of my data.

Realizing that I am about to write a pretty much write a matlab scripts / functions for that, would it make sense if I put it in this repo too?

**Comment by KirstieJane** [comment]
There's also the [bids-matlab](https://github.com/bids-standard/bids-matlab) repository? Maybe there? I don't really mind! The answer is definitely it would be great to capture them somewhere 😸 

THE COOLEST thing from my point of view would be for you to add to the wiki anything that you figure out about the derivatives RC1. I don't think we have a page on derivatives and if you have any digested summaries (eg FAQ type answers) that could go in the wiki I'm sure that would be super useful!

**Comment by Remi-Gau** [comment]
Good point! OK I will try to add something to WIKI as I go anyway.

AFAIK bids-matlab is software independent so I am not sure it belongs there.

I will start working on something and then we can find a home for it later.
