### ISSUE TITLE
Link to validator is incorrect.

### ISSUE THREAD

**Issue by dkp** [bids-standard/bids-starter-kit#109]
http://github.com/bids-standard/bids-starter-kit/wiki/bids-validator-info says 	
1. The BIDS Validator can be found at https://incf.github.io/bids-validator/#
BUT, the correct link is http://bids-standard.github.io/bids-validator/

**Comment by dorahermes** [comment]
Thank you! The link is now correct

**Comment by Remi-Gau** [comment]
@all-contributors please add @dkp  for bug
