### ISSUE TITLE
Cleaning up the Matlab code

### ISSUE THREAD

**Issue by dorahermes** [bids-standard/bids-starter-kit#112]
The /matlabCode/ snippet directory is becoming a little bit unorganized, is it ok to reorganize according to modality? Folders per modality would include:
/ieeg
/eeg
/func
/anat
/general
/other

**Comment by KirstieJane** [comment]
Sounds good to me - although what is the difference between that folder and the matlab code repo?

**Comment by dorahermes** [comment]
same folder - just adding subfolders

**Comment by Remi-Gau** [comment]
SGTM :-)

**Comment by KirstieJane** [comment]
Sorry - I mean this repository: 
https://github.com/bids-standard/bids-matlab

**Comment by Remi-Gau** [comment]
In short and AFAICT: the bids-matlab is an attempt to have an equivalent to pybids, so functions that allow you to crawl through your BIDS data set and get info about it.

Most of the code in the matlab section of the bids-starter kit are more to help people to populate their bids data set with the appropriate json and tsv files.

The only exception is the `bids_report.m` function I had written that is now incorporated in bids-matlab and can therefore be removed from the bids starter kit I suppose.

**Comment by dorahermes** [comment]
oh, thanks! I created a link on the wiki/Useful Links to bids-matlab

**Comment by dorahermes** [comment]
resolved with #134

**Comment by dorahermes** [comment]
thanks @Remi-Gau !
