### ISSUE TITLE
matlab code does not use built-in matlab functions to write json file

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#119]
The issue was raised on [neurostars](https://neurostars.org/t/matlabcode-in-bids-error-in-createbids-bold-json-full-line-349-undefined-function-or-variable-jsonwrite/3986)

Apparently the code relies in this [JSONio library](https://github.com/gllmflndn/JSONio) that should be added to the matlab/octave path.

The built-in functions for matlab are jsonencode and jsondecode. There are no equivalent functions for octave (4.4 or 5.1) AFAICT.

Other possibilities:
- spm12 uses the JSONio library by calling spm_jsonwrite and spm_jsonread and has other interesting functions to help you with BIDS.
- and if you don't want to download the whole of SPM just to write a json file, you also have the lighter version [BIDS/matlab](https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/%2Butil/jsonencode.m) that has a jsondecode and jsonencode functions taken from SPM but also allows to read a lot of information from the BIDS data set.

Will work on a PR to fix this.

**Comment by KirstieJane** [comment]
Thank you @Remi-Gau! Adding a bit of documentation and some updates to the code will be super helpful!

**Comment by Remi-Gau** [comment]
Will add documentation / updates as soon as we have decided on the best approach to this.

This would likely need to be mentioned in the wiki as well. Will take of that too once we got that sorted.

**Comment by dorahermes** [comment]
The wiki Metadata File Formats section points to this repository, would be good to include either set of functions in the Code and Wiki as long as it is consistent:

There are many toolboxes in Matlab for reading / writing JSON files. One example is:
https://github.com/gllmflndn/JSONio

**Comment by Remi-Gau** [comment]
> The wiki Metadata File Formats section points to this repository, would be good to include either set of functions in the Code and Wiki as long as it is consistent:
> 
> There are many toolboxes in Matlab for reading / writing JSON files. One example is:
> https://github.com/gllmflndn/JSONio

I missed that section in the wiki. Definitely makes sense to be consistent and mention it in the code.

**Comment by gllmflndn** [comment]
[jsonencode](https://www.mathworks.com/help/matlab/ref/jsonencode.html) / [jsondecode](https://www.mathworks.com/help/matlab/ref/jsonencode.html) were only introduced in MATLAB R2016b and I hope they will be available in Octave 6.1 [next year](https://savannah.gnu.org/bugs/?53100).

So, on the long run, these are the functions to use but in the meantime [JSONio](https://github.com/gllmflndn/JSONio) should work with any MATLAB/Octave version and should be syntax compatible (note that JSONio has extra features not available in MATLAB).

[bids.util.jsonencode](https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/%2Butil/jsonencode.m) is a wrapper on top of this and will use whatever implementation (SPM, JSONio, MATLAB) available.

Same story with `readtable`/`writetable` introduced in MATLAB R2013b but not yet available in Octave ([work in progress](https://github.com/apjanke/octave-table)). SPM has `spm_load`/`spm_save` wrapped in `bids.util.tsvread`.

Bit messy but was hoping to hide this in [bids.util](https://github.com/bids-standard/bids-matlab/tree/master/%2Bbids/%2Butil).

**Comment by Remi-Gau** [comment]
Wiki has been edited.

https://github.com/bids-standard/bids-starter-kit/wiki/Metadata-file-formats

If it checks out with you this issue should be closable.

**Comment by dorahermes** [comment]
Thank you! closing this issue :-)
