### ISSUE TITLE
test matlab code on Octave

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#125]
Just tested with Octave 4.2.2 and the scripts to create `.tsv` in the matlab code folder do not work because the table function is something different in Octave.

Might be good to improve that, no?

related to #112

**Comment by gllmflndn** [comment]
Hopefully Octave will support `table` soon:
https://github.com/apjanke/octave-tablicious
In the meantime, best would be add a wrapper similar to `bids.util.tsvread`:
https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/%2Butil/tsvread.m
but this time copying away `spm_save`:
https://github.com/spm/spm12/blob/master/spm_save.m

**Comment by dorahermes** [comment]
Thanks for noting this! @Remi-Gau would you be able to add a note to the wiki [metadata file formats](https://github.com/bids-standard/bids-starter-kit/wiki/Metadata-file-formats) on Octave and tsv files?

**Comment by Remi-Gau** [comment]
> Hopefully Octave will support `table` soon:
> https://github.com/apjanke/octave-tablicious
> In the meantime, best would be add a wrapper similar to `bids.util.tsvread`:
> https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/%2Butil/tsvread.m
> but this time copying away `spm_save`:
> https://github.com/spm/spm12/blob/master/spm_save.m

@gllmflndn Yeah I was thinking of reusing some of the SPM functions as you have done such a great job at making it octave compatible: I was not going to reinvent the wheel. 

@marcobarilari Interested in helping out with this?

**Comment by marcobarilari** [comment]
@Remi-Gau yes, I can help with that. Thanks!

**Comment by Remi-Gau** [comment]
@gllmflndn Just to be clear this would mean adding a functionality to bids-matlab, correct?

**Comment by gllmflndn** [comment]
Yes, take whatever is needed from `spm_save.m` (for `csv[.gz]` and `tsv[.gz]` files) and create `bids.util.tsvwrite`  in `bids-matlab`. The most recent version of `spm_save.m` is here:
https://gist.github.com/gllmflndn/605af3142a1a75a7c54d80b3d8cb7791

**Comment by Remi-Gau** [comment]
> Thanks for noting this! @Remi-Gau would you be able to add a note to the wiki [metadata file formats](https://github.com/bids-standard/bids-starter-kit/wiki/Metadata-file-formats) on Octave and tsv files?

update the wiki on that issue. :-)

**Comment by Remi-Gau** [comment]
Opened a PR on [bids-matlab](https://github.com/bids-standard/bids-matlab/pull/40) to solve that problem.

**Comment by Remi-Gau** [comment]
I added a tsv_write function in bids-matlab. might be good to change the code example accordingly, no?

pro:
-  this way it works for both octave and matlab

con:
- forces people to use bids-matlab

**Comment by dorahermes** [comment]
This is super useful. There may be 2 user groups here: one who just starts with BIDS/git, one who may want to join the development group in the future.

For first-time-BIDSers (assuming limited git experience), let's limit the number of packages to download and keep the read/write table option. 

For people who want to join the development more, we should absolutely point to bids-matlab.

Not sure which path to take for the code examples... (e.g. start a separate octaveCode or note in the Matlab code that octave users can replace those lines with bids-matlab functions?)

**Comment by Remi-Gau** [comment]
> This is super useful. There may be 2 user groups here: one who just starts with BIDS/git, one who may want to join the development group in the future.

Yay !!!

> For first-time-BIDSers (assuming limited git experience), let's limit the number of packages to download and keep the read/write table option.

Yes I think this is actually a reasonable choice

> For people who want to join the development more, we should absolutely point to bids-matlab

Well I know a couple of people who are coding bits and bobs of bids related code on matlab. I have some hope we could try to start centralizing it all in the bids-matlab repo... I don't mind leading the charge on that front but I would not want to be alone.

> Not sure which path to take for the code examples... (e.g. start a separate octaveCode or note in the Matlab code that octave users can replace those lines with bids-matlab functions?)

maybe a simple `try / catch` in the code ? I think there is already one here and there.

**Comment by dorahermes** [comment]
+1 on centralizing in the bids-matlab repo

+1 on the try/catch in the code

**Comment by gllmflndn** [comment]
Fully agree to try and have `bids-matlab` as the central repository for all BIDS-related MATLAB code. It would help preventing duplication of efforts and instead join efforts to build a clean and robust library.

Concerning `try/catch`, could you give an example of where it would be used? This might make the code less readable for a new user so perhaps a single syntax could be used in tutorials but indicating somewhere that there is a library available to deal with Octave, older MATLAB, etc?

**Comment by Remi-Gau** [comment]
I was thinking that since we already have some `try / catch` in our code scritps in this repo, we could just expand those: https://github.com/bids-standard/bids-starter-kit/blob/d4e6ed239f6f2c5623c4cfeb2f607b5c0efc3e7c/matlabCode/func/createBIDS_bold_json_full.m#L353

**Comment by Remi-Gau** [comment]
Talking about centralizing, I am unsure about where to put a link to some of the matlab/octave stuff my lab and I have been working on recently:

- https://github.com/cpp-lln-lab/CPP_BIDS (mostly to ouput "almost BIDS" stuff when running an experiment)
- https://github.com/cpp-lln-lab/CPP_BIDS_SPM_pipeline (not yet a BIDS app but I suspect this just yet another BIDS based SPM pipeline)

**Comment by Remi-Gau** [comment]
Closing since #281 implements bids-matlab in our code snippet and is Octave compatible
