### ISSUE TITLE
Inconsistent BIDS specification

### ISSUE THREAD

**Issue by civier** [bids-standard/bids-starter-kit#126]
There is inconsistencies in the BIDS specification between the information here:
https://bids-specification.readthedocs.io/en/stable/
and here:
https://github.com/bids-standard/bids-starter-kit/wiki/The-BIDS-folder-hierarchy
For example, in the file name format for the fmap files.
The spec always leads according to https://neurostars.org/t/inconsistant-bids-specification/5905/2, so the wiki of the BIDS starter kit should be amended.

**Comment by KirstieJane** [comment]
That’s great @civier! Are you about to make the changes?

**Comment by dorahermes** [comment]
Thanks for checking. Can you be specific as to exactly how they differ for fmap?
