### ISSUE TITLE
Guidelines for clinical electrophysiology research data 

### ISSUE THREAD

**Issue by dorahermes** [bids-standard/bids-starter-kit#127]
During the iEEG-BIDS and EEG-BIDS extensions, several issues were raised for storing large medical research electrophysiology datasets. We started a [google doc](https://docs.google.com/document/d/1ImuiRaynfu1fdy8ZG0Ab1bGLWDYa3Nplxa6jn7SoaGo/edit?usp=sharing) to address some of these questions and incorporate the answers in a set of guidelines in the bids-starter-kit wiki. These guidelines should provide tools and best practices for structuring clinical electrophysiology research data in BIDS. 

Clinical electrophysiology research involves machine learning methods and standard processing steps, such as epileptic spike detection, seizure detection, sleep staging, artifact rejection and visualization. These guidelines hope to make sure that there are standard recommendations and tools for medical electrophysiology research data and accompanying metadata that BIDS apps can run on and form a bridge with the medical community. 

This is an effort together with Jan Cimbalnik @cimbi

**Comment by Remi-Gau** [comment]
@dorahermes 
should I include what's already in this google doc on the starter kit and point to the google doc to explain that this is a work in progress?

**Comment by Remi-Gau** [comment]
OK closing then
