### ISSUE TITLE
Another BIDS tutorial

### ISSUE THREAD

**Issue by jdkent** [bids-standard/bids-starter-kit#129]
There is a BIDS tutorial given in [Andy's Brain Book](https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/BIDS_Overview.html), should this be included in the wiki under "[Other Tutorials](https://github.com/bids-standard/bids-starter-kit/wiki/Tutorials#other-tutorials)"?

**Comment by dorahermes** [comment]
Thank you. This is great, please go ahead and add it!

**Comment by jdkent** [comment]
Awesome, it should be in the [tutorial section now](https://github.com/bids-standard/bids-starter-kit/wiki/Tutorials#other-tutorials)

**Comment by Remi-Gau** [comment]
@all-contributors please add @jdkent  for ideas
