### ISSUE TITLE
[FAQ] how to make "good use" of the BIDS BEP before they are merged

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#135]
The issue was raised on the BIDS mailing list.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bids-discussion/nfoyuH46ckU/rYVTTv1kAwAJ

Could be good to add something about this in the FAQ. Would this be too "advanced" for the starter kit?

**Comment by dorahermes** [comment]
I also get questions like this (e.g. CT/derivatives are not yet part of BIDS, but still in extension proposal, what to do?).

**Comment by franklin-feingold** [comment]
initially, this could be part of the starter kit and we can move it around as we enhance our organization

What do you all think?

**Comment by dorahermes** [comment]
+1, thanks @franklin-feingold  

It seems also that everyone agreed on recommending the .bidsignore for these cases.

**Comment by Remi-Gau** [comment]
Yes I agree. 

And talking about the .bidsignore, that too should be in the FAQ. Yarik added a good pointer we could reuse.

Should I open another issue, so we remember? Or simply start a general FAQ issue with a checklist of the questions to add?

**Comment by emdupre** [comment]
I'd say that .bidsignore should be highlighted here in describing contributing to / working with BEPs, and then maybe again later in another section on dealing with non-bids-compliant data. I don't think the repetition would hurt !

**Comment by dorahermes** [comment]
I added the answer from the BIDS mailing list here:
https://github.com/bids-standard/bids-starter-kit/wiki/FAQ#is-your-data-type-not-covered-in-the-current-bids-specification

If this looks good to you @Remi-Gau @emdupre we can close this issue

**Comment by Remi-Gau** [comment]
Looks great to me

:-)



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by emdupre** [comment]
I added in a few missing links, but the content looks great ! Thanks, @dorahermes !
