### ISSUE TITLE
Setting up the all contributors bot?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#141]
Do we want to use it?

If so? Is that something we should do "now" or wait do it during the "rejuvenation" process that should happen "soon" on this repo?

**Comment by dorahermes** [comment]
I think it would be great to automatically recognize contributions, especially since we are keeping the code repository @franklin-feingold do you have any ideas?

**Comment by franklin-feingold** [comment]
sounds good to set up the contributor bot here! Recognizing contributors can be done while the enhancement process is further fleshed, that process may be a bit longer to ramp up and implement

**Comment by Remi-Gau** [comment]
OK I will "slowly" go through our backlog of issues and PR and start adding people as contributors.

**Comment by Remi-Gau** [comment]
Contributions type sort out:
- [ ] maintenance
- [ ] doc

**Comment by Remi-Gau** [comment]
Done with the pull request backlog.

Will go through the issues later.

**Comment by Remi-Gau** [comment]
also check list of commits in the wiki

**Comment by Remi-Gau** [comment]
- [x] checked the issues

**Comment by Remi-Gau** [comment]
List of contributors on the wiki:

```
git clone https://github.com/bids-standard/bids-starter-kit.wiki.git    
git shortlog -sne --all
```

dorahermes              
Park-Patrick            
Kirstie Whitaker        
Chris Holdgraf          
Robert Oostenveld       
Remi Gau                         
Stefan Appelhoff        
Anthony Galassi         
Chris Benjamin          
Isla                    
AlexandreHutton         
Ankit Gupta             
Anushka Bhandari        
Chris Filo Gorgolewski 
Chris Markiewicz        
Elizabeth DuPre         
Franklin Feingold       
James Kent              
alexvonlautz

**Comment by Remi-Gau** [comment]
@all-contributors please add @cfxb for doc

**Comment by Remi-Gau** [comment]
@all-contributors please add @Islast for doc

**Comment by Remi-Gau** [comment]
@all-contributors please add @effigies for doc

**Comment by Remi-Gau** [comment]
@all-contributors please add @ankiitgupta7 for doc

**Comment by Remi-Gau** [comment]
@all-contributors please add @alexvonlautz for doc

**Comment by Remi-Gau** [comment]
@all-contributors please add @AlexandreHutton for doc

**Comment by Remi-Gau** [comment]
Done!!
