### ISSUE TITLE
improve documentation on the derivatives

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#142]
This was pointed out at the last bids-matlab meeting: there is no content regarding BIDS derivatives in the starter-kit.

This seems like an URGENT low hanging fruit.

**Comment by effigies** [comment]
Here's some content: https://hackmd.io/@effigies/bids-derivatives-readme

**Comment by Remi-Gau** [comment]
Thanks @effigies 

OK if I grab the derivative part of that and reinject it the wiki?

Similarly, some of the BIDS app part could go and supplement our BIDS app FAQ.

**Comment by effigies** [comment]
Feel free to use any text verbatim, if it's useful.

**Comment by Remi-Gau** [comment]
Did  a "wild" copy paste of the core of that hackmd in the starter kit wiki.

Will refine it gradually. Hope this is OK.

**Comment by Remi-Gau** [comment]
closing this for now: the info is in the wiki
