### ISSUE TITLE
Add some minimum info or pointers on how what licence to choose

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#191]
Unless I have missed it, there seems to be very little (none?) info in the starter kit on what licence to choose.

At minima it would be nice to point to the Turing way page: https://the-turing-way.netlify.app/reproducible-research/licensing/licensing-data.html

**Comment by KirstieJane** [comment]
I remember Chris G having a super strong opinion about CC0 for data. Are there any constraints on data licences if you want to be part of OpenNeuro? Feels important to highlight if so?

**Comment by Remi-Gau** [comment]
> I remember Chris G having a super strong opinion about CC0 for data. Are there any constraints on data licences if you want to be part of OpenNeuro? Feels important to highlight if so?

Good point if some of the data repository have some constraints then it should probably be highlighted. 

I know [GIN](https://gin.g-node.org/) has none but this might not be the case everywhere.

**Comment by dorahermes** [comment]
This is an important point and I think it would be helpful to point out that this has to be considered at the stage of consent: https://open-brain-consent.readthedocs.io/en/stable/

**Comment by franklin-feingold** [comment]
Regarding OpenNeuro licenses, we only use a CC0 license for sharing data. In [our FAQ](https://openneuro.org/faq) we describe why we do not allow a CC-BY (or other CC licenses)
