### ISSUE TITLE
Storing raw CT scans for ieeg localization

### ISSUE THREAD

**Issue by Aaronearlerichardson** [bids-standard/bids-starter-kit#192]
I am trying to BIDSify some data collected by a lab performing ieeg research. I am looking for a BIDS compliant way to store anatomical CT scans. As far as I can tell, the only anatomical scans supported are MR. Did I miss something? What do you suggest?

If you need context [this](https://www.fieldtriptoolbox.org/tutorial/human_ecog/#fusion-of-the-ct-with-the-mri) is roughly the workflow

**Comment by Remi-Gau** [comment]
hey @Aaronearlerichardson 

You are correct that CT scans are not supported yet by BIDS.

When faced with a modality I am not sure how to handle I usually check if there is an BIDS extension proposal (BEP) about it.

They are all listed there.
https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification

Luckliy for you there is one for CT :rocket: 
https://docs.google.com/document/d/1fqnJZ18x5LJC8jiJ8yvPHUGFzNBZ6gW2kywYrUKWtuo/edit

So I would suggest you use the content of the BEP to start helping you organize your data.

My other suggestion would be to actually comment and report any questions and suggestions in the google doc of that BEP. That is usually very useful to the BEP creation process and that can be a first step to actually contribute to BIDS. :smile: 

 About how to keep the bids validator happy until it supports this new modality: have a look at the answer in the FAQ.
 
 https://github.com/bids-standard/bids-starter-kit/wiki/FAQ#is-your-data-type-not-covered-in-the-current-bids-specification
 
 Hope this helps. Let me know if you have more questions.

**Comment by Aaronearlerichardson** [comment]
Thank you this is very helpful! It is often hard to know when trying to BIDSify for a new modality whether you are missing something or not. Thank you for your reply!

**Comment by Remi-Gau** [comment]
Glad I could help. :smile_cat:
