### ISSUE TITLE
Add "hyperscanning" to FAQ

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#195]
if only by pointing to existing issues and discussions.

**Comment by Remi-Gau** [comment]
- https://groups.google.com/g/bids-discussion/c/v660DuzOf3w/m/q-0PLHt5BgAJ
- https://github.com/bids-standard/bids-specification/issues/402

**Comment by christinerogers** [comment]
can i reopen this on the website repo ? @julia-pfarr    Just got this question at BrainHackMtl 
 thoughts @Remi-Gau ?

**Comment by Remi-Gau** [comment]
there is an entry in the FAQ of the website: https://bids.neuroimaging.io/faq/general.html#how-should-i-organize-data-for-hyperscanning-data

probably could be improved

**Comment by julia-pfarr** [comment]
@christinerogers what do you mean by reopen this on the website repo? What exactly should we do on the website? If you or someone else have a clear proposal what to put on the website you can open an issue on the website repo or better a PR with modifications or for how to improve the FAQ entry that Remi pointed to above
