### ISSUE TITLE
provide input and test "bids_spreadsheet2participants"

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#202]
This matlab function would be more useful if it came with some example input.

I tried to create some but I could not test as I do not have a Matlab version that's recent enough.

https://github.com/bids-standard/bids-starter-kit/tree/master/matlabCode/general

**Comment by CPernet** [comment]
what do you want me to do here? give an excel sheet example

**Comment by Remi-Gau** [comment]
if you have one lying around it'd be great. :-)

got my hand on a more recent matlab so I should be able to test things out.

also if I add comments to the function, on which repo does it live in more permanent fashion?

**Comment by CPernet** [comment]
this is the permanent repo where it lives -  I created it for here (and a project in which people needed to convert excel)
