### ISSUE TITLE
[idea] create a datacamp course about BIDSs

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/bids-starter-kit#22]
DataCamp is an online training platform that includes web based data related courses with game like features. More info at https://www.datacamp.com/teach/

**Comment by KirstieJane** [comment]
Iiiinteresting. I'm going to leave this for anyone who fancies it! Sounds like something the GSoC student could investigate.

Not necessary from my point of view, but if it sounds fun (for the developer and the learners) then I'm totally down!

**Comment by Remi-Gau** [comment]
going to close this in favor of pointing people towards the BIDS carpentry work
