### ISSUE TITLE
Link to docs broken

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-starter-kit#228]
The link to web page on right of repository page under "About" is broken. Thanks....

**Comment by Remi-Gau** [comment]
Thanks for spotting this: this should be fixed now, but FYI this is just a different render of the landing page.

Most of the information is actually in the wiki: https://github.com/bids-standard/bids-starter-kit/wiki

And I have working a bit on the side to use mkdocs for the starter kit too: https://remi-gau.github.io/BIDS-Starter-Kit/index.html

Also been playing around with a jupyter book version that lives on this branch for now: https://github.com/Remi-Gau/BIDS-Starter-Kit/tree/book

Hoping to one day show this to the community to see which way people prefer to go.
