### ISSUE TITLE
Some links that might be put in

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-starter-kit#253]
- [x] On the menu on the side of the [BIDS web site](https://bids-specification.readthedocs.io/en/stable/), the sidebar link to Tutorials goes to the starter-kit GitHub page.  I think it should go to the starter-kit website.

- [x] On the [BIDS Starter Kit website](https://bids-standard.github.io/bids-starter-kit/) there is no link to the Templates directory.  A natural thing would be to put a link under the RESOURCES category.

**Comment by Remi-Gau** [comment]
Good points both. Will open PR on each for those.

**Comment by Remi-Gau** [comment]
Added a link in the TOC in the starter kit: right below the folders and filenames sections.

**Comment by Remi-Gau** [comment]
> * On the menu on the side of the [BIDS web site](https://bids-specification.readthedocs.io/en/stable/), the sidebar link to Tutorials goes to the starter-kit GitHub page.  I think it should go to the starter-kit website.

This is actually already fixed in the latest version of the specs: that you can always view at this URL.

https://bids-specification.readthedocs.io/en/latest/
