### ISSUE TITLE
Session definition _too restrictive_?

### ISSUE THREAD

**Issue by SamGuay** [bids-standard/bids-starter-kit#265]
I was reading the BIDS starter kit and I felt that the `session` definition was a little bit _<s>misleading</s>_ restrictive. According to the current specs (1.7.0), a session can represent more than _just_ a recording session: 

From the [1.7.0 specs](https://bids-specification.readthedocs.io/en/v1.7.0/02-common-principles.html#definitions):
> A logical grouping of neuroimaging and behavioral data consistent across subjects. Session can (but doesn't have to) be synonymous to a visit in a longitudinal study. In general, subjects will stay in the scanner during one session.

VS

In the [starter kit](https://bids-standard.github.io/bids-starter-kit/folders_and_files/folders.html#session): 
> Represents a recording session. You might have multiple sessions per subject if you collected data from them on different days. If there is only a single session per subject, this level of the hierarchy may be omitted.

Was the starter kit definition simplified to make it easier to understand or the session definition has evolved over time? I've stumbled upon this as I'm working on a project for which sessions are week-based instead of recording-based.

Thanks

**Comment by Remi-Gau** [comment]
I think that this was simplified for the purpose of the starter kit. I think that `sessions` as a logical grouping has been in BIDS since the beginning. But you are correct that this the phrasing in the starter kit is too restrictive.

Minimal change to make it more correct:

> **In many cases** this represents a recording session and you might have multiple sessions per subject if you collected data from them on different days. If there is only a single session per subject, this level of the hierarchy may be omitted.

Maybe we should also link to this question of the FAQ: https://bids-standard.github.io/bids-starter-kit/faq.html#i-had-to-split-the-testing-of-one-of-my-participants-across-2-days-should-i-use-2-different-session-folders-to-organize-the-data-of-that-participant

WDYT?

**Comment by SamGuay** [comment]
First, I think restrictive is the word I was looking for!

The minimal change is good, I think it leaves room for other use cases. And definitely, a link to the FAQ would be great. I personally didn't even notice the FAQ or even thought the answer could have been in it.

**Comment by Remi-Gau** [comment]
> I didn't event notice

Should pretty much be the subtitle of the starter kit... I wish it were not so.

Can I let you PR this change?

**Comment by VisLab** [comment]
I think it is very important to preserve the "subjects will stay in the scanner during one session" for a session.
There are strong analysis reasons to distinguish recordings that involve a single positioning of the scanner from those that do not.

**Comment by Remi-Gau** [comment]
> I think it is very important to preserve the "subjects will stay in the scanner during one session" for a session. There are strong analysis reasons to distinguish recordings that involve a single positioning of the scanner from those that do not.

Fine with me as long as we also include the "in general" from that same sentence from the spec.

**Comment by SamGuay** [comment]
I would keep the _in general_ as well considering the question in the [FAQ](https://bids-standard.github.io/bids-starter-kit/faq.html#i-had-to-split-the-testing-of-one-of-my-participants-across-2-days-should-i-use-2-different-session-folders-to-organize-the-data-of-that-participant) literally says: 
> ... you can put in the same session folder data that were acquired on different days...

That being said, I would be interested in reading more about the strong analysis reasons you had in mind @VisLab, if you have some quick references to share, that'd be great. I could include some more info in the FAQ as well so people are aware of said reasons.

**Comment by VisLab** [comment]
The assumption that a session consists of a "single placement of the scanner (headset)" is critical for EEG.  EEG signals are significantly affected by scalp, hair, and skull, so replacement of the headset can introduce significant variations in the results.
This makes it difficult to isolate sources of variability. Most EEG datasets do not have reference MRI's and most current analysis assumes a "standard cap" and a "standard" meaning of electrodes, irrespective of the actual properties of an individual's head.
While not knowing the "exact position" of an electrode relative to an individual's brain, one can deduce differences that are the result of the task or other factors such as the time-on-task provided that the positions of the electrodes are fixed for the duration.

If you aren't going to enforce fixed position in the scanner for a session, the data set info should clearly state that.

**Comment by Remi-Gau** [comment]
Closed by #266
