### ISSUE TITLE
PowerLineFrequency in the eeg.json file not working

### ISSUE THREAD

**Issue by ChengtengIp** [bids-standard/bids-starter-kit#269]
Hi,

I use bids-matlab-tool-master to create the bids folder. In the GUI, there is an option where I can choose the PowerLineFrequency for the EEG. However, it won't convert into the number I want. It is n/a and BIDS validator did give me a warning. I believe that it is the format of the input from GUI. 

Best regards,
Cheng-Teng

**Comment by Remi-Gau** [comment]
hey @ChengtengIp 
just to make sure, is this a bids stater kit issue or a bids-matlab-tool issue?

**Comment by ChengtengIp** [comment]
It is a bids-matlab-tool issue

**Comment by Remi-Gau** [comment]
ok closing this then
