### ISSUE TITLE
Individual vs Orig space?

### ISSUE THREAD

**Issue by CPLambert** [bids-standard/bids-starter-kit#304]
Hi there,

There appears to be 2 (or 3) variations on the theme of original subject space of the source data for bids file-naming and SpatialReference JSON fields. "orig" seems to be widely used throughout v.1.8 (and earlier), although in the list of "Must be one of" terms under the spatial reference entry, orig is missing and the term "individual" is used (which seems to pervade more through the fMRI arm of BIDS cf. structural), with passing mention to "fsnative" just to add to the mix......

Is there a difference here? Either-way, I'd suggest adding "orig" to the list of accepted "SpatialReference" field entries given how prevalent it is now.

Cheers

Chris

**Comment by Remi-Gau** [comment]
hey @CPLambert 

It seems that this issue in the BIDS specification overlaps with your concern. Am I correct?

https://github.com/bids-standard/bids-specification/issues/1486

If so I would suggest to make comments over there rather than in the BIDS starter kit.
