### ISSUE TITLE
Establish Zotero collection of citations

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-starter-kit#305]
To be up to date, and be ready to be used for anyone using Zotero. Should contain citations for BEPs, e.g. pointing to WiP documents/PRs and eventually to the corresponding representative papers or sections in the bids-specification.

Not sure if this repo is the best for such issue, feel welcome to move.

attn @jbpoline  @dbkeator with whom we are struggling ATM without having such a thing ;)

**Comment by Remi-Gau** [comment]
Like having a Zotero group and we link to it from the starter kit?

**Comment by yarikoptic** [comment]
yeah... there was also something about "grants writing" so should be linked there too

**Comment by Remi-Gau** [comment]
ah yeah we did circulate a "grant writing starter kit" internally but kind of obvious it may have some useful resources for others
