### ISSUE TITLE
links and resources is ... underwhelming

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-starter-kit#306]
I was looking for a list of tools and got to https://bids-standard.github.io/bids-starter-kit/links.html which seems to be really "basic".
Should point to BIDS-Apps, various other currently existing, possible get rid of outdated/no longer developed like https://github.com/robertoostenveld/bids-tools (with @robertoostenveld blessing)

or may be there is already some other location collating those, then just point [there](https://bids.neuroimaging.io/benefits.html) instead of having this mediocre smth.

**Comment by Remi-Gau** [comment]
Agreed to have a single place for them all.
Either have eveyrything on the website or everything on the starter kit.
Feel like the starter kit you give more flexibility.

**Comment by Remi-Gau** [comment]
Will close this one as the bids starter kit will be merged into the main BIDS website.
