### ISSUE TITLE
Add R Code for templates

### ISSUE THREAD

**Issue by anushkab** [bids-standard/bids-starter-kit#35]
Hey
We currently don't have a RCodes folder. Some users will be looking for R files to generate different templates.
I set up R environment for the same and I think it would be great to have ReadMe in RCode Folder where links to setting up R environment for different distributions will be given. Also, the README will be linked to the repo's wiki (Metadata file formats ) for the ease of our users. 
I would like to create the requisite R files for template generation.

Regards
Anushka

**Comment by KirstieJane** [comment]
Hi @anushkab - that idea sounds good to me. Go for it 😸

**Comment by Remi-Gau** [comment]
Should probably make mention of this: https://github.com/bbuchsbaum/bidser

**Comment by Remi-Gau** [comment]
Will close this because of the move to the new BIDS website where several R tools are already mentioned.
