### ISSUE TITLE
Stats on the wiki

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-starter-kit#43]
It would be great if the wiki could include statistics about who's making contributions so that we can say "thanks" to members of the community that participate. I found out that you can git-clone the wiki with the following incantation:

```
git clone https://github.com/incf/bids-starter-kit.wiki.git
```

We can use whatever git-analytics approach we like to pull out user stats from this. Alternatively we could create a new dummy repository within INCF called something like `wiki-stats` and the only thing we'd do is occasionally update that repository with the git repo for the wiki. Then I think GitHub's pre-existing repo stats dashboarding would work.

Here's the process, from how I see it:

## General overview

The Wiki for the bids starter kit is stored in its own git repository, this lives at:

https://github.com/incf/bids-starter-kit.wiki.git

However we don't have access to the typical GitHub statistics because GH doesn't expose this UI for wikis. So, how can we get "GitHub repository statistics plots for a wiki?"

## Solution

Use a "traditional" GitHub repository to mirror all of the changes that happen in the wiki. Since GitHub thinks it's just a "regular" github repository, it'll expose all of the plots for user activity.

## Steps

1. Set up a repository that will mirror the start kit wiki (e.g. `INCF/bids-starter-kit-wiki`)
2. Git clone the repository to your computer
3. Add the wiki repository as a "remote" in git
 
   ```
   git remote add wiki https://github.com/incf/bids-starter-kit.wiki.git
   ```
4. Now pull in the latest changes to the wiki into your local "wiki mirror" repository
   
   ```
   git pull wiki master
   ```
5. Finally, push the local repository back to the "wiki mirror" repository on github:
   ```
   git push
   ```

Thoughts? cc @KirstieJane

**Comment by choldgraf** [comment]
actually turns out stats etc is quite easy. I just tried this with a test repo on my account. All you need to do is run the clone command above, then:

```
git remote add newrepo https://github.com/incf/wiki-stats
git push newrepo master
```

and it'll update `newrepo` with the latest state of the wiki. E.g. here's what it looks like on my temp repo:

https://github.com/choldgraf/tmp_test/graphs/contributors

![image](https://user-images.githubusercontent.com/1839645/37568262-fa819be2-2ad2-11e8-926d-9c0fb6a26c67.png)

**Comment by KirstieJane** [comment]
I LIKE IT! I'd love to be able to show off anyone contributing to the wiki ✨ 

I don't have time to work on this, but I'm going to leave the issue open and anyone in the community is welcome to make it their own. The only thing I care about is making it easy to celebrate people adding to the BIDS starter kit 🎉

**Comment by choldgraf** [comment]
so I think the path forward here is to:

1. Create a repo called "bids-starter-kit-wiki-stats" (or something like this)
2. Occasionally clone the wiki for this repo (`git clone https://github.com/incf/bids-starter-kit.wiki.git`) and push it to the `wiki-stats` repo we've created.
3. Create links in the wiki / other places online to the dashboard for wiki-stats so that we can say "thanks" to people

**Comment by KirstieJane** [comment]
Gotcha - sounds good to me. Thanks @choldgraf.

I wonder if that's something that could be automated? To update somewhat regularly?

This issue is open for anyone who wants to expand on the plan! I think it's likely a **good first contribution** so if you think you can help, please do! ✨

**Comment by choldgraf** [comment]
for sure - definitely scriptable at the least (e.g. `python update_wiki_stats.py`) though you'd need push access to the repo to do it. It could be automated to run on cloud infastructure somewhere...maybe a cron job that runs on whatever hosts OpenNeuro? cc @chrisfilo

**Comment by chrisfilo** [comment]
What about https://support.circleci.com/hc/en-us/articles/115015481128-Scheduling-jobs-cron-for-builds- ?

**Comment by choldgraf** [comment]
First of all: whoah, I hadn't seen that before but it looks super useful ✨ ✨ ✨ 

Secondly: yeah we should totally look into this for automating the process :-)

**Comment by Park-Patrick** [comment]
Seems like it would be cool idea to have these stats! 
I just looked into both circleCI and travisCI:
for pricing, it seems like they'd both be free circle(one free container) travis(all open-source free)
for the technical process, I haven't used either of them, so I'm inclined to go with whichever is more proven. 
What are your opinions on this?

**Comment by KirstieJane** [comment]
Hey @choldgraf! I was chatting with @Park-Patrick at OHBM and he mentioned that he wasn't super sure where to start on this front! I also don't really know how to get this off the ground.

I can tweet the issue and see if anyone from the community wants to help? What do you think? 

The alternative is that you might be able to do the work, but I know you're super busy so I'm really just giving your first refusal here ✨

**Comment by KirstieJane** [comment]
Wooooo! I did it! https://github.com/INCF/bids-starter-kit-wiki

Thank you to @rmarkello for helping me with an additional `git rebase wiki/master` and `git push --force` which I think happened because I added a README *before* linking the wiki to the new repo.

Easy to see the stats, as you said @choldgraf, at https://github.com/INCF/bids-starter-kit-wiki/graphs/contributors

![image](https://user-images.githubusercontent.com/3626306/43976626-28dddc5a-9c96-11e8-94da-54f0b0122905.png)

**Comment by KirstieJane** [comment]
We do *not* have a continuous integration way of doing this - I think we need a server for that - so at the moment my plan is to basically `git pull wiki/master; git push` whenever I'm curious about the updates and....erm....that might have to be the best we do for now 😆 😬 🤷‍♀️

**Comment by chrisfilo** [comment]
https://support.circleci.com/hc/en-us/articles/115015481128-Scheduling-jobs-cron-for-builds-

**Comment by KirstieJane** [comment]
Thanks @chrisfilo - I do know that it's technically possible but it's outside of my skillset and I don't have time to figure it out.

If you do, that would be amazing ❤️
