### ISSUE TITLE
Update BIDS website (http://bids.neuroimaging.io) with information from Starter Kit README

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bids-starter-kit#74]
The main landing page for anyone searching for information about BIDS is http://bids.neuroimaging.io.

@Park-Patrick has done great work updating the BIDS Starter Kit README with lots of useful information about the background and motivations for BIDS, and this information could also be brought over to the main website (http://bids.neuroimaging.io) (as suggested by @chrisfilo in our discussions in #70).

The pull request would have to go to https://github.com/INCF/BIDS rather than to this repository, but I thought having the discussion of what to transfer over might make sense.

Any thoughts on what should be included on the main website?

**Comment by chrisfilo** [comment]
I think everything seems relevant with exception of "Contributing" section which has content specific to the bids starter kit repository.

**Comment by Park-Patrick** [comment]
Okay I'd be happy to port some of our README over to the main website -- but what'll be our process of deciding which info from either repo stays?

I've tried to roughly pair the corresponding sections with each other below
(main on left, starter kit on right):

* About BIDS <--> Project Summary
* No equivalent <--> Intro Video (somewhat specific to starter kit)
* Getting started (links to starter-kit) <--> How do I find information?
* Software currently supporting BIDS <--> no equivalent
* Spread throughout <--> Philosophy
* No equivalent <--> Motivation (Text is specific to Starter kit)
* Benefits <--> Benefits
* No equivalent <--> Users
* Get involved in making BIDS better <--> No equivalent
* Acknowledgements / contributing / etc. are different

My initial suggestion would be to keep the BIDS website as is and add the non-redundant starter kit info into the "Getting started" section. Happy to hear any thoughts on this!

**Comment by KirstieJane** [comment]
@Park-Patrick and I have chatted in person today and he's going to work on updating the "Getting started" and "Get involved" sections - making sure to link to the starter kit from each of those sections.

Patrick - make sure to include Neurostars in the getting started section - it isn't mentioned at the moment and I think more details on contact make sense ✨ 

Plan is not to revamp the whole website - that's a bit too much for his last week in GSOC....but hopefully to at least add in some useful content.

**Comment by chrisfilo** [comment]
Great! Looking forward!

BTW I think link to Neurostars is there:
![image](https://user-images.githubusercontent.com/238759/43783142-d51bfc46-9a15-11e8-9f62-9fdd021a35f5.png)

**Comment by KirstieJane** [comment]
Ah - yes - gotcha. So @Park-Patrick I suppose the clearer feedback is adding your *description* of neurostars to the getting started section so that it's easier to know what you're clicking on.

@chrisfilo - do you have any preferences about language style (short, formal) etc for the main website? I think the most useful way forward is for @Park-Patrick to do a first draft and for you to make edits to fit the style you're looking for. Does that sound ok?

**Comment by Remi-Gau** [comment]
Will close this one given the coming move of the bids stater kit into the bids website
