### ISSUE TITLE
Cleaning comments create*.m scripts in matlab code

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#87]
Hey all,
Does anyone mind if I do some cleaning of the comments in the matlab code folder? 
Mostly the fact that matlab EDI does not wrap automatically so unless users have a abnormally large screen this will using this script less convenient.
Also... it trigger my OCD tendencies. ;-p
Remi

**Comment by emdupre** [comment]
That sounds great, @Remi-Gau ! PR welcome :+1:

**Comment by Remi-Gau** [comment]
Now in #89

**Comment by dorahermes** [comment]
#89 is merged, can we close this?
