### ISSUE TITLE
Permission error when downloading the example data set 

### ISSUE THREAD

**Issue by ilkayisik** [bids-standard/bids-starter-kit#92]
BIDS Tutorial Series > Part 1a: Introductory Walkthrough prompts to download DICOMs from the  [Nathan Kline Institute (NKI) Rockland Sample – Multiband Imaging Test-Retest Pilot Dataset.](http://fcon_1000.projects.nitrc.org/indi/pro/eNKI_RS_TRT/FrontPage.html)
For me is not possible to do the download and I get this error: 
<img width="1005" alt="nitrc_error" src="https://user-images.githubusercontent.com/22478219/45544974-28066100-b819-11e8-86ff-b2342c8917e5.png">

I was wondering if this is a general issue, then would be great if it is fixed.
Thanks!

**Comment by KirstieJane** [comment]
Hi @ilkayisik! I think you need to get permission from NKI to access the data. So this isn't an *error* to fix on NITRC but in the tutorial (we need to tell you that you need permission!)

Unfortunately I **do** have access so I'm having difficulty developing those instructions (where to click etc). Can you see any button to apply for that access?

I can try to have a play around over the weekend (in a few meetings today) but I'll also add a `help wanted` tag in case anyone else can help you out sooner!

**Comment by Park-Patrick** [comment]
Hi @ilkayisik thanks for the heads up about this issue!

I've just uploaded some instructions / screenshots for the process of getting access.

Let me know how it works for you! https://imgur.com/a/hMkM7rA

![capture](https://user-images.githubusercontent.com/12662110/45588087-08387100-b8dd-11e8-8658-d3c15c6dc92f.PNG)
![capture4](https://user-images.githubusercontent.com/12662110/45588088-0cfd2500-b8dd-11e8-8e46-8d7439ca55f2.PNG)
![capture2](https://user-images.githubusercontent.com/12662110/45588089-0ff81580-b8dd-11e8-89d4-269cd56ea24b.PNG)
![capture3](https://user-images.githubusercontent.com/12662110/45588090-138b9c80-b8dd-11e8-9f19-6f44e29e513f.PNG)

**Comment by Park-Patrick** [comment]
@KirstieJane I'm not too familiar with NITRC's access protocols. Could you please verify if the method above seems ok?

**Comment by ilkayisik** [comment]
Hi @Park-Patrick ,
I have completed this steps and waiting for the reply from the administrators for the access. But seems like this is the process yes and would be great if this is mentioned in the wiki.

**Comment by ilkayisik** [comment]
Hi again, 
Update: the data download is possible after registering NITRC and requesting access!

**Comment by KirstieJane** [comment]
Fantastic! Thank you @ilkayisik!

@Park-Patrick, @franklin-feingold or @ilkayisik - has this information been captured in the wiki or in the tutorials anywhere?

**Comment by Park-Patrick** [comment]
Hi everyone,

@ilkayisik great to hear that it worked! 

@KirstieJane @franklin-feingold , the page is [here](https://github.com/bids-standard/bids-starter-kit/wiki/Tutorials-FAQ) under Tutorials FAQ. 

I think it'll be useful to have an open-ended page like this (as opposed to on the Stanford Repro Site) that can be easily edited to since there have been some other questions about the tutorials that can be added, but happy to hear your thoughts too

**Comment by franklin-feingold** [comment]
Thank you @Park-Patrick ! I think this is great and answers the questions I have seen regarding the tutorial blogpost. I have added a link to your tutorial in the blog post on the first step (where you need to download the data).

**Comment by Remi-Gau** [comment]
closing as the page is now in the book
