### ISSUE TITLE
EEG "little templates"

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-starter-kit#97]
I would like to add templates with added descriptions for EEG related issues:

1. How to specify filters in the correct JSON format
2. How to specify "active reference systems" like CMS/DRL by Biosemi

for that, I'd create some snippets in `/templates/...`. But accompanying these templates I would like to write a bit of markdown text.

Where should I place that?

- In a README, nested in `templates/...` next to my example snippets?
- In the WIKI?
- some other place?

**Comment by dorahermes** [comment]
Nice! I think the WIKI would be a good place? @KirstieJane
