### ISSUE TITLE
python script to generate MP2RAGE json

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#99]
Hey,
I have recently written my first python script that did not blow up my house and it was made to create the MP2RAGE json files for my BIDS data sets (to fit the way they are described in the current state of the BIDS extension).
I am wondering if there is any point of adding this script to this repo as this extension is not finalized yet as as we seem to have a json scripts inflation issue that needs for uniformization (#47 #57 #58 ).
@+
Remi

**Comment by KirstieJane** [comment]
Hi @Remi-Gau!

You're right that we haven't quite formalised #57 but I think more is better than less to get started. For example the harmonise across languages issue #58 makes the most sense if there are a few to harmonise!

I also feel the same way about having tools that are for extensions - in my opinion its the more the merrier at this stage....but maybe add the date to a comment at the top of the file and highlight that the spec may change and therefore this may end up being out of date?
